
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Products: 'Products',
  CartItems: 'CartItems',
  PurchasedProduct: 'PurchasedProduct'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ProductsScalarFieldEnum = {
  id: 'id',
  productTitle: 'productTitle',
  productName: 'productName',
  image: 'image',
  description: 'description',
  price: 'price',
  category: 'category',
  gender: 'gender'
} as const

export type ProductsScalarFieldEnum = (typeof ProductsScalarFieldEnum)[keyof typeof ProductsScalarFieldEnum]


export const CartItemsScalarFieldEnum = {
  cartId: 'cartId',
  productId: 'productId',
  userId: 'userId',
  total_Amount: 'total_Amount',
  color: 'color',
  Quantity: 'Quantity',
  size: 'size',
  viewCart: 'viewCart',
  show_cart: 'show_cart'
} as const

export type CartItemsScalarFieldEnum = (typeof CartItemsScalarFieldEnum)[keyof typeof CartItemsScalarFieldEnum]


export const PurchasedProductScalarFieldEnum = {
  acquiredId: 'acquiredId',
  productId: 'productId',
  TransactionString: 'TransactionString',
  PhoneNumber: 'PhoneNumber',
  Amount: 'Amount',
  Location: 'Location',
  MerchantRequestID: 'MerchantRequestID',
  product: 'product',
  ResultCode: 'ResultCode'
} as const

export type PurchasedProductScalarFieldEnum = (typeof PurchasedProductScalarFieldEnum)[keyof typeof PurchasedProductScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const ProductsOrderByRelevanceFieldEnum = {
  id: 'id',
  productTitle: 'productTitle',
  productName: 'productName',
  image: 'image',
  description: 'description',
  category: 'category',
  gender: 'gender'
} as const

export type ProductsOrderByRelevanceFieldEnum = (typeof ProductsOrderByRelevanceFieldEnum)[keyof typeof ProductsOrderByRelevanceFieldEnum]


export const CartItemsOrderByRelevanceFieldEnum = {
  cartId: 'cartId',
  productId: 'productId',
  userId: 'userId',
  color: 'color',
  size: 'size',
  show_cart: 'show_cart'
} as const

export type CartItemsOrderByRelevanceFieldEnum = (typeof CartItemsOrderByRelevanceFieldEnum)[keyof typeof CartItemsOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const PurchasedProductOrderByRelevanceFieldEnum = {
  acquiredId: 'acquiredId',
  productId: 'productId',
  TransactionString: 'TransactionString',
  PhoneNumber: 'PhoneNumber',
  Location: 'Location',
  MerchantRequestID: 'MerchantRequestID',
  product: 'product',
  ResultCode: 'ResultCode'
} as const

export type PurchasedProductOrderByRelevanceFieldEnum = (typeof PurchasedProductOrderByRelevanceFieldEnum)[keyof typeof PurchasedProductOrderByRelevanceFieldEnum]

