/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CartItems` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model CartItems
 *
 */
export type CartItemsModel =
  runtime.Types.Result.DefaultSelection<Prisma.$CartItemsPayload>;

export type AggregateCartItems = {
  _count: CartItemsCountAggregateOutputType | null;
  _avg: CartItemsAvgAggregateOutputType | null;
  _sum: CartItemsSumAggregateOutputType | null;
  _min: CartItemsMinAggregateOutputType | null;
  _max: CartItemsMaxAggregateOutputType | null;
};

export type CartItemsAvgAggregateOutputType = {
  total_Amount: number | null;
  Quantity: number | null;
};

export type CartItemsSumAggregateOutputType = {
  total_Amount: number | null;
  Quantity: number | null;
};

export type CartItemsMinAggregateOutputType = {
  cartId: string | null;
  productId: string | null;
  userId: string | null;
  total_Amount: number | null;
  color: string | null;
  Quantity: number | null;
  size: string | null;
  viewCart: boolean | null;
};

export type CartItemsMaxAggregateOutputType = {
  cartId: string | null;
  productId: string | null;
  userId: string | null;
  total_Amount: number | null;
  color: string | null;
  Quantity: number | null;
  size: string | null;
  viewCart: boolean | null;
};

export type CartItemsCountAggregateOutputType = {
  cartId: number;
  productId: number;
  userId: number;
  total_Amount: number;
  color: number;
  Quantity: number;
  size: number;
  viewCart: number;
  _all: number;
};

export type CartItemsAvgAggregateInputType = {
  total_Amount?: true;
  Quantity?: true;
};

export type CartItemsSumAggregateInputType = {
  total_Amount?: true;
  Quantity?: true;
};

export type CartItemsMinAggregateInputType = {
  cartId?: true;
  productId?: true;
  userId?: true;
  total_Amount?: true;
  color?: true;
  Quantity?: true;
  size?: true;
  viewCart?: true;
};

export type CartItemsMaxAggregateInputType = {
  cartId?: true;
  productId?: true;
  userId?: true;
  total_Amount?: true;
  color?: true;
  Quantity?: true;
  size?: true;
  viewCart?: true;
};

export type CartItemsCountAggregateInputType = {
  cartId?: true;
  productId?: true;
  userId?: true;
  total_Amount?: true;
  color?: true;
  Quantity?: true;
  size?: true;
  viewCart?: true;
  _all?: true;
};

export type CartItemsAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which CartItems to aggregate.
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CartItems to fetch.
   */
  orderBy?:
    | Prisma.CartItemsOrderByWithRelationInput
    | Prisma.CartItemsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CartItemsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CartItems from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CartItems.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned CartItems
   **/
  _count?: true | CartItemsCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: CartItemsAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: CartItemsSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CartItemsMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CartItemsMaxAggregateInputType;
};

export type GetCartItemsAggregateType<T extends CartItemsAggregateArgs> = {
  [P in keyof T & keyof AggregateCartItems]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCartItems[P]>
    : Prisma.GetScalarType<T[P], AggregateCartItems[P]>;
};

export type CartItemsGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.CartItemsWhereInput;
  orderBy?:
    | Prisma.CartItemsOrderByWithAggregationInput
    | Prisma.CartItemsOrderByWithAggregationInput[];
  by: Prisma.CartItemsScalarFieldEnum[] | Prisma.CartItemsScalarFieldEnum;
  having?: Prisma.CartItemsScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: CartItemsCountAggregateInputType | true;
  _avg?: CartItemsAvgAggregateInputType;
  _sum?: CartItemsSumAggregateInputType;
  _min?: CartItemsMinAggregateInputType;
  _max?: CartItemsMaxAggregateInputType;
};

export type CartItemsGroupByOutputType = {
  cartId: string;
  productId: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart: boolean | null;
  _count: CartItemsCountAggregateOutputType | null;
  _avg: CartItemsAvgAggregateOutputType | null;
  _sum: CartItemsSumAggregateOutputType | null;
  _min: CartItemsMinAggregateOutputType | null;
  _max: CartItemsMaxAggregateOutputType | null;
};

export type GetCartItemsGroupByPayload<T extends CartItemsGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<CartItemsGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof CartItemsGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CartItemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CartItemsGroupByOutputType[P]>;
      }
    >
  >;

export type CartItemsWhereInput = {
  AND?: Prisma.CartItemsWhereInput | Prisma.CartItemsWhereInput[];
  OR?: Prisma.CartItemsWhereInput[];
  NOT?: Prisma.CartItemsWhereInput | Prisma.CartItemsWhereInput[];
  cartId?: Prisma.StringFilter<"CartItems"> | string;
  productId?: Prisma.StringFilter<"CartItems"> | string;
  userId?: Prisma.StringFilter<"CartItems"> | string;
  total_Amount?: Prisma.IntFilter<"CartItems"> | number;
  color?: Prisma.StringFilter<"CartItems"> | string;
  Quantity?: Prisma.IntFilter<"CartItems"> | number;
  size?: Prisma.StringFilter<"CartItems"> | string;
  viewCart?: Prisma.BoolNullableFilter<"CartItems"> | boolean | null;
  pId?: Prisma.XOR<
    Prisma.ProductsScalarRelationFilter,
    Prisma.ProductsWhereInput
  >;
};

export type CartItemsOrderByWithRelationInput = {
  cartId?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  total_Amount?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
  size?: Prisma.SortOrder;
  viewCart?: Prisma.SortOrderInput | Prisma.SortOrder;
  pId?: Prisma.ProductsOrderByWithRelationInput;
  _relevance?: Prisma.CartItemsOrderByRelevanceInput;
};

export type CartItemsWhereUniqueInput = Prisma.AtLeast<
  {
    cartId?: string;
    productId?: string;
    AND?: Prisma.CartItemsWhereInput | Prisma.CartItemsWhereInput[];
    OR?: Prisma.CartItemsWhereInput[];
    NOT?: Prisma.CartItemsWhereInput | Prisma.CartItemsWhereInput[];
    userId?: Prisma.StringFilter<"CartItems"> | string;
    total_Amount?: Prisma.IntFilter<"CartItems"> | number;
    color?: Prisma.StringFilter<"CartItems"> | string;
    Quantity?: Prisma.IntFilter<"CartItems"> | number;
    size?: Prisma.StringFilter<"CartItems"> | string;
    viewCart?: Prisma.BoolNullableFilter<"CartItems"> | boolean | null;
    pId?: Prisma.XOR<
      Prisma.ProductsScalarRelationFilter,
      Prisma.ProductsWhereInput
    >;
  },
  "cartId" | "productId"
>;

export type CartItemsOrderByWithAggregationInput = {
  cartId?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  total_Amount?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
  size?: Prisma.SortOrder;
  viewCart?: Prisma.SortOrderInput | Prisma.SortOrder;
  _count?: Prisma.CartItemsCountOrderByAggregateInput;
  _avg?: Prisma.CartItemsAvgOrderByAggregateInput;
  _max?: Prisma.CartItemsMaxOrderByAggregateInput;
  _min?: Prisma.CartItemsMinOrderByAggregateInput;
  _sum?: Prisma.CartItemsSumOrderByAggregateInput;
};

export type CartItemsScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.CartItemsScalarWhereWithAggregatesInput
    | Prisma.CartItemsScalarWhereWithAggregatesInput[];
  OR?: Prisma.CartItemsScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.CartItemsScalarWhereWithAggregatesInput
    | Prisma.CartItemsScalarWhereWithAggregatesInput[];
  cartId?: Prisma.StringWithAggregatesFilter<"CartItems"> | string;
  productId?: Prisma.StringWithAggregatesFilter<"CartItems"> | string;
  userId?: Prisma.StringWithAggregatesFilter<"CartItems"> | string;
  total_Amount?: Prisma.IntWithAggregatesFilter<"CartItems"> | number;
  color?: Prisma.StringWithAggregatesFilter<"CartItems"> | string;
  Quantity?: Prisma.IntWithAggregatesFilter<"CartItems"> | number;
  size?: Prisma.StringWithAggregatesFilter<"CartItems"> | string;
  viewCart?:
    | Prisma.BoolNullableWithAggregatesFilter<"CartItems">
    | boolean
    | null;
};

export type CartItemsCreateInput = {
  cartId?: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart?: boolean | null;
  pId: Prisma.ProductsCreateNestedOneWithoutCartInput;
};

export type CartItemsUncheckedCreateInput = {
  cartId?: string;
  productId: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart?: boolean | null;
};

export type CartItemsUpdateInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  pId?: Prisma.ProductsUpdateOneRequiredWithoutCartNestedInput;
};

export type CartItemsUncheckedUpdateInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  productId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type CartItemsCreateManyInput = {
  cartId?: string;
  productId: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart?: boolean | null;
};

export type CartItemsUpdateManyMutationInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type CartItemsUncheckedUpdateManyInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  productId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type CartItemsListRelationFilter = {
  every?: Prisma.CartItemsWhereInput;
  some?: Prisma.CartItemsWhereInput;
  none?: Prisma.CartItemsWhereInput;
};

export type CartItemsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type CartItemsOrderByRelevanceInput = {
  fields:
    | Prisma.CartItemsOrderByRelevanceFieldEnum
    | Prisma.CartItemsOrderByRelevanceFieldEnum[];
  sort: Prisma.SortOrder;
  search: string;
};

export type CartItemsCountOrderByAggregateInput = {
  cartId?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  total_Amount?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
  size?: Prisma.SortOrder;
  viewCart?: Prisma.SortOrder;
};

export type CartItemsAvgOrderByAggregateInput = {
  total_Amount?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
};

export type CartItemsMaxOrderByAggregateInput = {
  cartId?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  total_Amount?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
  size?: Prisma.SortOrder;
  viewCart?: Prisma.SortOrder;
};

export type CartItemsMinOrderByAggregateInput = {
  cartId?: Prisma.SortOrder;
  productId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  total_Amount?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
  size?: Prisma.SortOrder;
  viewCart?: Prisma.SortOrder;
};

export type CartItemsSumOrderByAggregateInput = {
  total_Amount?: Prisma.SortOrder;
  Quantity?: Prisma.SortOrder;
};

export type CartItemsCreateNestedManyWithoutPIdInput = {
  create?:
    | Prisma.XOR<
        Prisma.CartItemsCreateWithoutPIdInput,
        Prisma.CartItemsUncheckedCreateWithoutPIdInput
      >
    | Prisma.CartItemsCreateWithoutPIdInput[]
    | Prisma.CartItemsUncheckedCreateWithoutPIdInput[];
  connectOrCreate?:
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput[];
  createMany?: Prisma.CartItemsCreateManyPIdInputEnvelope;
  connect?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
};

export type CartItemsUncheckedCreateNestedManyWithoutPIdInput = {
  create?:
    | Prisma.XOR<
        Prisma.CartItemsCreateWithoutPIdInput,
        Prisma.CartItemsUncheckedCreateWithoutPIdInput
      >
    | Prisma.CartItemsCreateWithoutPIdInput[]
    | Prisma.CartItemsUncheckedCreateWithoutPIdInput[];
  connectOrCreate?:
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput[];
  createMany?: Prisma.CartItemsCreateManyPIdInputEnvelope;
  connect?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
};

export type CartItemsUpdateManyWithoutPIdNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CartItemsCreateWithoutPIdInput,
        Prisma.CartItemsUncheckedCreateWithoutPIdInput
      >
    | Prisma.CartItemsCreateWithoutPIdInput[]
    | Prisma.CartItemsUncheckedCreateWithoutPIdInput[];
  connectOrCreate?:
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput[];
  upsert?:
    | Prisma.CartItemsUpsertWithWhereUniqueWithoutPIdInput
    | Prisma.CartItemsUpsertWithWhereUniqueWithoutPIdInput[];
  createMany?: Prisma.CartItemsCreateManyPIdInputEnvelope;
  set?: Prisma.CartItemsWhereUniqueInput | Prisma.CartItemsWhereUniqueInput[];
  disconnect?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
  delete?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
  connect?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
  update?:
    | Prisma.CartItemsUpdateWithWhereUniqueWithoutPIdInput
    | Prisma.CartItemsUpdateWithWhereUniqueWithoutPIdInput[];
  updateMany?:
    | Prisma.CartItemsUpdateManyWithWhereWithoutPIdInput
    | Prisma.CartItemsUpdateManyWithWhereWithoutPIdInput[];
  deleteMany?:
    | Prisma.CartItemsScalarWhereInput
    | Prisma.CartItemsScalarWhereInput[];
};

export type CartItemsUncheckedUpdateManyWithoutPIdNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CartItemsCreateWithoutPIdInput,
        Prisma.CartItemsUncheckedCreateWithoutPIdInput
      >
    | Prisma.CartItemsCreateWithoutPIdInput[]
    | Prisma.CartItemsUncheckedCreateWithoutPIdInput[];
  connectOrCreate?:
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput
    | Prisma.CartItemsCreateOrConnectWithoutPIdInput[];
  upsert?:
    | Prisma.CartItemsUpsertWithWhereUniqueWithoutPIdInput
    | Prisma.CartItemsUpsertWithWhereUniqueWithoutPIdInput[];
  createMany?: Prisma.CartItemsCreateManyPIdInputEnvelope;
  set?: Prisma.CartItemsWhereUniqueInput | Prisma.CartItemsWhereUniqueInput[];
  disconnect?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
  delete?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
  connect?:
    | Prisma.CartItemsWhereUniqueInput
    | Prisma.CartItemsWhereUniqueInput[];
  update?:
    | Prisma.CartItemsUpdateWithWhereUniqueWithoutPIdInput
    | Prisma.CartItemsUpdateWithWhereUniqueWithoutPIdInput[];
  updateMany?:
    | Prisma.CartItemsUpdateManyWithWhereWithoutPIdInput
    | Prisma.CartItemsUpdateManyWithWhereWithoutPIdInput[];
  deleteMany?:
    | Prisma.CartItemsScalarWhereInput
    | Prisma.CartItemsScalarWhereInput[];
};

export type IntFieldUpdateOperationsInput = {
  set?: number;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
};

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null;
};

export type CartItemsCreateWithoutPIdInput = {
  cartId?: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart?: boolean | null;
};

export type CartItemsUncheckedCreateWithoutPIdInput = {
  cartId?: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart?: boolean | null;
};

export type CartItemsCreateOrConnectWithoutPIdInput = {
  where: Prisma.CartItemsWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.CartItemsCreateWithoutPIdInput,
    Prisma.CartItemsUncheckedCreateWithoutPIdInput
  >;
};

export type CartItemsCreateManyPIdInputEnvelope = {
  data:
    | Prisma.CartItemsCreateManyPIdInput
    | Prisma.CartItemsCreateManyPIdInput[];
  skipDuplicates?: boolean;
};

export type CartItemsUpsertWithWhereUniqueWithoutPIdInput = {
  where: Prisma.CartItemsWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.CartItemsUpdateWithoutPIdInput,
    Prisma.CartItemsUncheckedUpdateWithoutPIdInput
  >;
  create: Prisma.XOR<
    Prisma.CartItemsCreateWithoutPIdInput,
    Prisma.CartItemsUncheckedCreateWithoutPIdInput
  >;
};

export type CartItemsUpdateWithWhereUniqueWithoutPIdInput = {
  where: Prisma.CartItemsWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.CartItemsUpdateWithoutPIdInput,
    Prisma.CartItemsUncheckedUpdateWithoutPIdInput
  >;
};

export type CartItemsUpdateManyWithWhereWithoutPIdInput = {
  where: Prisma.CartItemsScalarWhereInput;
  data: Prisma.XOR<
    Prisma.CartItemsUpdateManyMutationInput,
    Prisma.CartItemsUncheckedUpdateManyWithoutPIdInput
  >;
};

export type CartItemsScalarWhereInput = {
  AND?: Prisma.CartItemsScalarWhereInput | Prisma.CartItemsScalarWhereInput[];
  OR?: Prisma.CartItemsScalarWhereInput[];
  NOT?: Prisma.CartItemsScalarWhereInput | Prisma.CartItemsScalarWhereInput[];
  cartId?: Prisma.StringFilter<"CartItems"> | string;
  productId?: Prisma.StringFilter<"CartItems"> | string;
  userId?: Prisma.StringFilter<"CartItems"> | string;
  total_Amount?: Prisma.IntFilter<"CartItems"> | number;
  color?: Prisma.StringFilter<"CartItems"> | string;
  Quantity?: Prisma.IntFilter<"CartItems"> | number;
  size?: Prisma.StringFilter<"CartItems"> | string;
  viewCart?: Prisma.BoolNullableFilter<"CartItems"> | boolean | null;
};

export type CartItemsCreateManyPIdInput = {
  cartId?: string;
  userId: string;
  total_Amount: number;
  color: string;
  Quantity: number;
  size: string;
  viewCart?: boolean | null;
};

export type CartItemsUpdateWithoutPIdInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type CartItemsUncheckedUpdateWithoutPIdInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type CartItemsUncheckedUpdateManyWithoutPIdInput = {
  cartId?: Prisma.StringFieldUpdateOperationsInput | string;
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  total_Amount?: Prisma.IntFieldUpdateOperationsInput | number;
  color?: Prisma.StringFieldUpdateOperationsInput | string;
  Quantity?: Prisma.IntFieldUpdateOperationsInput | number;
  size?: Prisma.StringFieldUpdateOperationsInput | string;
  viewCart?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type CartItemsSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    cartId?: boolean;
    productId?: boolean;
    userId?: boolean;
    total_Amount?: boolean;
    color?: boolean;
    Quantity?: boolean;
    size?: boolean;
    viewCart?: boolean;
    pId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["cartItems"]
>;

export type CartItemsSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    cartId?: boolean;
    productId?: boolean;
    userId?: boolean;
    total_Amount?: boolean;
    color?: boolean;
    Quantity?: boolean;
    size?: boolean;
    viewCart?: boolean;
    pId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["cartItems"]
>;

export type CartItemsSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    cartId?: boolean;
    productId?: boolean;
    userId?: boolean;
    total_Amount?: boolean;
    color?: boolean;
    Quantity?: boolean;
    size?: boolean;
    viewCart?: boolean;
    pId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["cartItems"]
>;

export type CartItemsSelectScalar = {
  cartId?: boolean;
  productId?: boolean;
  userId?: boolean;
  total_Amount?: boolean;
  color?: boolean;
  Quantity?: boolean;
  size?: boolean;
  viewCart?: boolean;
};

export type CartItemsOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "cartId"
  | "productId"
  | "userId"
  | "total_Amount"
  | "color"
  | "Quantity"
  | "size"
  | "viewCart",
  ExtArgs["result"]["cartItems"]
>;
export type CartItemsInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  pId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>;
};
export type CartItemsIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  pId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>;
};
export type CartItemsIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  pId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>;
};

export type $CartItemsPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "CartItems";
  objects: {
    pId: Prisma.$ProductsPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      cartId: string;
      productId: string;
      userId: string;
      total_Amount: number;
      color: string;
      Quantity: number;
      size: string;
      viewCart: boolean | null;
    },
    ExtArgs["result"]["cartItems"]
  >;
  composites: {};
};

export type CartItemsGetPayload<
  S extends boolean | null | undefined | CartItemsDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$CartItemsPayload, S>;

export type CartItemsCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<CartItemsFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: CartItemsCountAggregateInputType | true;
};

export interface CartItemsDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["CartItems"];
    meta: { name: "CartItems" };
  };
  /**
   * Find zero or one CartItems that matches the filter.
   * @param {CartItemsFindUniqueArgs} args - Arguments to find a CartItems
   * @example
   * // Get one CartItems
   * const cartItems = await prisma.cartItems.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CartItemsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CartItemsFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one CartItems that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CartItemsFindUniqueOrThrowArgs} args - Arguments to find a CartItems
   * @example
   * // Get one CartItems
   * const cartItems = await prisma.cartItems.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CartItemsFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, CartItemsFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CartItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsFindFirstArgs} args - Arguments to find a CartItems
   * @example
   * // Get one CartItems
   * const cartItems = await prisma.cartItems.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CartItemsFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CartItemsFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CartItems that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsFindFirstOrThrowArgs} args - Arguments to find a CartItems
   * @example
   * // Get one CartItems
   * const cartItems = await prisma.cartItems.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CartItemsFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, CartItemsFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more CartItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CartItems
   * const cartItems = await prisma.cartItems.findMany()
   *
   * // Get first 10 CartItems
   * const cartItems = await prisma.cartItems.findMany({ take: 10 })
   *
   * // Only select the `cartId`
   * const cartItemsWithCartIdOnly = await prisma.cartItems.findMany({ select: { cartId: true } })
   *
   */
  findMany<T extends CartItemsFindManyArgs>(
    args?: Prisma.SelectSubset<T, CartItemsFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a CartItems.
   * @param {CartItemsCreateArgs} args - Arguments to create a CartItems.
   * @example
   * // Create one CartItems
   * const CartItems = await prisma.cartItems.create({
   *   data: {
   *     // ... data to create a CartItems
   *   }
   * })
   *
   */
  create<T extends CartItemsCreateArgs>(
    args: Prisma.SelectSubset<T, CartItemsCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many CartItems.
   * @param {CartItemsCreateManyArgs} args - Arguments to create many CartItems.
   * @example
   * // Create many CartItems
   * const cartItems = await prisma.cartItems.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CartItemsCreateManyArgs>(
    args?: Prisma.SelectSubset<T, CartItemsCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many CartItems and returns the data saved in the database.
   * @param {CartItemsCreateManyAndReturnArgs} args - Arguments to create many CartItems.
   * @example
   * // Create many CartItems
   * const cartItems = await prisma.cartItems.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many CartItems and only return the `cartId`
   * const cartItemsWithCartIdOnly = await prisma.cartItems.createManyAndReturn({
   *   select: { cartId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends CartItemsCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, CartItemsCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a CartItems.
   * @param {CartItemsDeleteArgs} args - Arguments to delete one CartItems.
   * @example
   * // Delete one CartItems
   * const CartItems = await prisma.cartItems.delete({
   *   where: {
   *     // ... filter to delete one CartItems
   *   }
   * })
   *
   */
  delete<T extends CartItemsDeleteArgs>(
    args: Prisma.SelectSubset<T, CartItemsDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one CartItems.
   * @param {CartItemsUpdateArgs} args - Arguments to update one CartItems.
   * @example
   * // Update one CartItems
   * const cartItems = await prisma.cartItems.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CartItemsUpdateArgs>(
    args: Prisma.SelectSubset<T, CartItemsUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more CartItems.
   * @param {CartItemsDeleteManyArgs} args - Arguments to filter CartItems to delete.
   * @example
   * // Delete a few CartItems
   * const { count } = await prisma.cartItems.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CartItemsDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, CartItemsDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CartItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CartItems
   * const cartItems = await prisma.cartItems.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CartItemsUpdateManyArgs>(
    args: Prisma.SelectSubset<T, CartItemsUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CartItems and returns the data updated in the database.
   * @param {CartItemsUpdateManyAndReturnArgs} args - Arguments to update many CartItems.
   * @example
   * // Update many CartItems
   * const cartItems = await prisma.cartItems.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more CartItems and only return the `cartId`
   * const cartItemsWithCartIdOnly = await prisma.cartItems.updateManyAndReturn({
   *   select: { cartId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends CartItemsUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, CartItemsUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one CartItems.
   * @param {CartItemsUpsertArgs} args - Arguments to update or create a CartItems.
   * @example
   * // Update or create a CartItems
   * const cartItems = await prisma.cartItems.upsert({
   *   create: {
   *     // ... data to create a CartItems
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CartItems we want to update
   *   }
   * })
   */
  upsert<T extends CartItemsUpsertArgs>(
    args: Prisma.SelectSubset<T, CartItemsUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__CartItemsClient<
    runtime.Types.Result.GetResult<
      Prisma.$CartItemsPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of CartItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsCountArgs} args - Arguments to filter CartItems to count.
   * @example
   * // Count the number of CartItems
   * const count = await prisma.cartItems.count({
   *   where: {
   *     // ... the filter for the CartItems we want to count
   *   }
   * })
   **/
  count<T extends CartItemsCountArgs>(
    args?: Prisma.Subset<T, CartItemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], CartItemsCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a CartItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CartItemsAggregateArgs>(
    args: Prisma.Subset<T, CartItemsAggregateArgs>,
  ): Prisma.PrismaPromise<GetCartItemsAggregateType<T>>;

  /**
   * Group by CartItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CartItemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CartItemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CartItemsGroupByArgs["orderBy"] }
      : { orderBy?: CartItemsGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, CartItemsGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetCartItemsGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the CartItems model
   */
  readonly fields: CartItemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CartItems.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CartItemsClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  pId<T extends Prisma.ProductsDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ProductsDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__ProductsClient<
    | runtime.Types.Result.GetResult<
        Prisma.$ProductsPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the CartItems model
 */
export interface CartItemsFieldRefs {
  readonly cartId: Prisma.FieldRef<"CartItems", "String">;
  readonly productId: Prisma.FieldRef<"CartItems", "String">;
  readonly userId: Prisma.FieldRef<"CartItems", "String">;
  readonly total_Amount: Prisma.FieldRef<"CartItems", "Int">;
  readonly color: Prisma.FieldRef<"CartItems", "String">;
  readonly Quantity: Prisma.FieldRef<"CartItems", "Int">;
  readonly size: Prisma.FieldRef<"CartItems", "String">;
  readonly viewCart: Prisma.FieldRef<"CartItems", "Boolean">;
}

// Custom InputTypes
/**
 * CartItems findUnique
 */
export type CartItemsFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * Filter, which CartItems to fetch.
   */
  where: Prisma.CartItemsWhereUniqueInput;
};

/**
 * CartItems findUniqueOrThrow
 */
export type CartItemsFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * Filter, which CartItems to fetch.
   */
  where: Prisma.CartItemsWhereUniqueInput;
};

/**
 * CartItems findFirst
 */
export type CartItemsFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * Filter, which CartItems to fetch.
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CartItems to fetch.
   */
  orderBy?:
    | Prisma.CartItemsOrderByWithRelationInput
    | Prisma.CartItemsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CartItems.
   */
  cursor?: Prisma.CartItemsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CartItems from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CartItems.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CartItems.
   */
  distinct?:
    | Prisma.CartItemsScalarFieldEnum
    | Prisma.CartItemsScalarFieldEnum[];
};

/**
 * CartItems findFirstOrThrow
 */
export type CartItemsFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * Filter, which CartItems to fetch.
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CartItems to fetch.
   */
  orderBy?:
    | Prisma.CartItemsOrderByWithRelationInput
    | Prisma.CartItemsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CartItems.
   */
  cursor?: Prisma.CartItemsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CartItems from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CartItems.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CartItems.
   */
  distinct?:
    | Prisma.CartItemsScalarFieldEnum
    | Prisma.CartItemsScalarFieldEnum[];
};

/**
 * CartItems findMany
 */
export type CartItemsFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * Filter, which CartItems to fetch.
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CartItems to fetch.
   */
  orderBy?:
    | Prisma.CartItemsOrderByWithRelationInput
    | Prisma.CartItemsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing CartItems.
   */
  cursor?: Prisma.CartItemsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CartItems from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CartItems.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CartItems.
   */
  distinct?:
    | Prisma.CartItemsScalarFieldEnum
    | Prisma.CartItemsScalarFieldEnum[];
};

/**
 * CartItems create
 */
export type CartItemsCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * The data needed to create a CartItems.
   */
  data: Prisma.XOR<
    Prisma.CartItemsCreateInput,
    Prisma.CartItemsUncheckedCreateInput
  >;
};

/**
 * CartItems createMany
 */
export type CartItemsCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many CartItems.
   */
  data: Prisma.CartItemsCreateManyInput | Prisma.CartItemsCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * CartItems createManyAndReturn
 */
export type CartItemsCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * The data used to create many CartItems.
   */
  data: Prisma.CartItemsCreateManyInput | Prisma.CartItemsCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * CartItems update
 */
export type CartItemsUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * The data needed to update a CartItems.
   */
  data: Prisma.XOR<
    Prisma.CartItemsUpdateInput,
    Prisma.CartItemsUncheckedUpdateInput
  >;
  /**
   * Choose, which CartItems to update.
   */
  where: Prisma.CartItemsWhereUniqueInput;
};

/**
 * CartItems updateMany
 */
export type CartItemsUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update CartItems.
   */
  data: Prisma.XOR<
    Prisma.CartItemsUpdateManyMutationInput,
    Prisma.CartItemsUncheckedUpdateManyInput
  >;
  /**
   * Filter which CartItems to update
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * Limit how many CartItems to update.
   */
  limit?: number;
};

/**
 * CartItems updateManyAndReturn
 */
export type CartItemsUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * The data used to update CartItems.
   */
  data: Prisma.XOR<
    Prisma.CartItemsUpdateManyMutationInput,
    Prisma.CartItemsUncheckedUpdateManyInput
  >;
  /**
   * Filter which CartItems to update
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * Limit how many CartItems to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * CartItems upsert
 */
export type CartItemsUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * The filter to search for the CartItems to update in case it exists.
   */
  where: Prisma.CartItemsWhereUniqueInput;
  /**
   * In case the CartItems found by the `where` argument doesn't exist, create a new CartItems with this data.
   */
  create: Prisma.XOR<
    Prisma.CartItemsCreateInput,
    Prisma.CartItemsUncheckedCreateInput
  >;
  /**
   * In case the CartItems was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.CartItemsUpdateInput,
    Prisma.CartItemsUncheckedUpdateInput
  >;
};

/**
 * CartItems delete
 */
export type CartItemsDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
  /**
   * Filter which CartItems to delete.
   */
  where: Prisma.CartItemsWhereUniqueInput;
};

/**
 * CartItems deleteMany
 */
export type CartItemsDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which CartItems to delete
   */
  where?: Prisma.CartItemsWhereInput;
  /**
   * Limit how many CartItems to delete.
   */
  limit?: number;
};

/**
 * CartItems without action
 */
export type CartItemsDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CartItems
   */
  select?: Prisma.CartItemsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CartItems
   */
  omit?: Prisma.CartItemsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemsInclude<ExtArgs> | null;
};
