
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PurchasedProduct` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PurchasedProduct
 * 
 */
export type PurchasedProductModel = runtime.Types.Result.DefaultSelection<Prisma.$PurchasedProductPayload>

export type AggregatePurchasedProduct = {
  _count: PurchasedProductCountAggregateOutputType | null
  _avg: PurchasedProductAvgAggregateOutputType | null
  _sum: PurchasedProductSumAggregateOutputType | null
  _min: PurchasedProductMinAggregateOutputType | null
  _max: PurchasedProductMaxAggregateOutputType | null
}

export type PurchasedProductAvgAggregateOutputType = {
  Amount: number | null
}

export type PurchasedProductSumAggregateOutputType = {
  Amount: number | null
}

export type PurchasedProductMinAggregateOutputType = {
  acquiredId: string | null
  productId: string | null
  TransactionString: string | null
  PhoneNumber: string | null
  Amount: number | null
  Location: string | null
  MerchantRequestID: string | null
  product: string | null
  ResultCode: string | null
}

export type PurchasedProductMaxAggregateOutputType = {
  acquiredId: string | null
  productId: string | null
  TransactionString: string | null
  PhoneNumber: string | null
  Amount: number | null
  Location: string | null
  MerchantRequestID: string | null
  product: string | null
  ResultCode: string | null
}

export type PurchasedProductCountAggregateOutputType = {
  acquiredId: number
  productId: number
  TransactionString: number
  PhoneNumber: number
  Amount: number
  Location: number
  MerchantRequestID: number
  product: number
  ResultCode: number
  _all: number
}


export type PurchasedProductAvgAggregateInputType = {
  Amount?: true
}

export type PurchasedProductSumAggregateInputType = {
  Amount?: true
}

export type PurchasedProductMinAggregateInputType = {
  acquiredId?: true
  productId?: true
  TransactionString?: true
  PhoneNumber?: true
  Amount?: true
  Location?: true
  MerchantRequestID?: true
  product?: true
  ResultCode?: true
}

export type PurchasedProductMaxAggregateInputType = {
  acquiredId?: true
  productId?: true
  TransactionString?: true
  PhoneNumber?: true
  Amount?: true
  Location?: true
  MerchantRequestID?: true
  product?: true
  ResultCode?: true
}

export type PurchasedProductCountAggregateInputType = {
  acquiredId?: true
  productId?: true
  TransactionString?: true
  PhoneNumber?: true
  Amount?: true
  Location?: true
  MerchantRequestID?: true
  product?: true
  ResultCode?: true
  _all?: true
}

export type PurchasedProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PurchasedProduct to aggregate.
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PurchasedProducts to fetch.
   */
  orderBy?: Prisma.PurchasedProductOrderByWithRelationInput | Prisma.PurchasedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PurchasedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PurchasedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PurchasedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PurchasedProducts
  **/
  _count?: true | PurchasedProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PurchasedProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PurchasedProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PurchasedProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PurchasedProductMaxAggregateInputType
}

export type GetPurchasedProductAggregateType<T extends PurchasedProductAggregateArgs> = {
      [P in keyof T & keyof AggregatePurchasedProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePurchasedProduct[P]>
    : Prisma.GetScalarType<T[P], AggregatePurchasedProduct[P]>
}




export type PurchasedProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PurchasedProductWhereInput
  orderBy?: Prisma.PurchasedProductOrderByWithAggregationInput | Prisma.PurchasedProductOrderByWithAggregationInput[]
  by: Prisma.PurchasedProductScalarFieldEnum[] | Prisma.PurchasedProductScalarFieldEnum
  having?: Prisma.PurchasedProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PurchasedProductCountAggregateInputType | true
  _avg?: PurchasedProductAvgAggregateInputType
  _sum?: PurchasedProductSumAggregateInputType
  _min?: PurchasedProductMinAggregateInputType
  _max?: PurchasedProductMaxAggregateInputType
}

export type PurchasedProductGroupByOutputType = {
  acquiredId: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount: number
  Location: string
  MerchantRequestID: string
  product: string
  ResultCode: string
  _count: PurchasedProductCountAggregateOutputType | null
  _avg: PurchasedProductAvgAggregateOutputType | null
  _sum: PurchasedProductSumAggregateOutputType | null
  _min: PurchasedProductMinAggregateOutputType | null
  _max: PurchasedProductMaxAggregateOutputType | null
}

export type GetPurchasedProductGroupByPayload<T extends PurchasedProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PurchasedProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PurchasedProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PurchasedProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PurchasedProductGroupByOutputType[P]>
      }
    >
  >



export type PurchasedProductWhereInput = {
  AND?: Prisma.PurchasedProductWhereInput | Prisma.PurchasedProductWhereInput[]
  OR?: Prisma.PurchasedProductWhereInput[]
  NOT?: Prisma.PurchasedProductWhereInput | Prisma.PurchasedProductWhereInput[]
  acquiredId?: Prisma.StringFilter<"PurchasedProduct"> | string
  productId?: Prisma.StringFilter<"PurchasedProduct"> | string
  TransactionString?: Prisma.StringFilter<"PurchasedProduct"> | string
  PhoneNumber?: Prisma.StringFilter<"PurchasedProduct"> | string
  Amount?: Prisma.IntFilter<"PurchasedProduct"> | number
  Location?: Prisma.StringFilter<"PurchasedProduct"> | string
  MerchantRequestID?: Prisma.StringFilter<"PurchasedProduct"> | string
  product?: Prisma.StringFilter<"PurchasedProduct"> | string
  ResultCode?: Prisma.StringFilter<"PurchasedProduct"> | string
  purchasedId?: Prisma.XOR<Prisma.ProductsScalarRelationFilter, Prisma.ProductsWhereInput>
}

export type PurchasedProductOrderByWithRelationInput = {
  acquiredId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  TransactionString?: Prisma.SortOrder
  PhoneNumber?: Prisma.SortOrder
  Amount?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  MerchantRequestID?: Prisma.SortOrder
  product?: Prisma.SortOrder
  ResultCode?: Prisma.SortOrder
  purchasedId?: Prisma.ProductsOrderByWithRelationInput
  _relevance?: Prisma.PurchasedProductOrderByRelevanceInput
}

export type PurchasedProductWhereUniqueInput = Prisma.AtLeast<{
  acquiredId?: string
  AND?: Prisma.PurchasedProductWhereInput | Prisma.PurchasedProductWhereInput[]
  OR?: Prisma.PurchasedProductWhereInput[]
  NOT?: Prisma.PurchasedProductWhereInput | Prisma.PurchasedProductWhereInput[]
  productId?: Prisma.StringFilter<"PurchasedProduct"> | string
  TransactionString?: Prisma.StringFilter<"PurchasedProduct"> | string
  PhoneNumber?: Prisma.StringFilter<"PurchasedProduct"> | string
  Amount?: Prisma.IntFilter<"PurchasedProduct"> | number
  Location?: Prisma.StringFilter<"PurchasedProduct"> | string
  MerchantRequestID?: Prisma.StringFilter<"PurchasedProduct"> | string
  product?: Prisma.StringFilter<"PurchasedProduct"> | string
  ResultCode?: Prisma.StringFilter<"PurchasedProduct"> | string
  purchasedId?: Prisma.XOR<Prisma.ProductsScalarRelationFilter, Prisma.ProductsWhereInput>
}, "acquiredId">

export type PurchasedProductOrderByWithAggregationInput = {
  acquiredId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  TransactionString?: Prisma.SortOrder
  PhoneNumber?: Prisma.SortOrder
  Amount?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  MerchantRequestID?: Prisma.SortOrder
  product?: Prisma.SortOrder
  ResultCode?: Prisma.SortOrder
  _count?: Prisma.PurchasedProductCountOrderByAggregateInput
  _avg?: Prisma.PurchasedProductAvgOrderByAggregateInput
  _max?: Prisma.PurchasedProductMaxOrderByAggregateInput
  _min?: Prisma.PurchasedProductMinOrderByAggregateInput
  _sum?: Prisma.PurchasedProductSumOrderByAggregateInput
}

export type PurchasedProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.PurchasedProductScalarWhereWithAggregatesInput | Prisma.PurchasedProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.PurchasedProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PurchasedProductScalarWhereWithAggregatesInput | Prisma.PurchasedProductScalarWhereWithAggregatesInput[]
  acquiredId?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  productId?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  TransactionString?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  PhoneNumber?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  Amount?: Prisma.IntWithAggregatesFilter<"PurchasedProduct"> | number
  Location?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  MerchantRequestID?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  product?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
  ResultCode?: Prisma.StringWithAggregatesFilter<"PurchasedProduct"> | string
}

export type PurchasedProductCreateInput = {
  acquiredId?: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount?: number
  Location: string
  MerchantRequestID?: string
  ResultCode?: string
  purchasedId: Prisma.ProductsCreateNestedOneWithoutPurchasedInput
}

export type PurchasedProductUncheckedCreateInput = {
  acquiredId?: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount?: number
  Location: string
  MerchantRequestID?: string
  product: string
  ResultCode?: string
}

export type PurchasedProductUpdateInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
  purchasedId?: Prisma.ProductsUpdateOneRequiredWithoutPurchasedNestedInput
}

export type PurchasedProductUncheckedUpdateInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PurchasedProductCreateManyInput = {
  acquiredId?: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount?: number
  Location: string
  MerchantRequestID?: string
  product: string
  ResultCode?: string
}

export type PurchasedProductUpdateManyMutationInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PurchasedProductUncheckedUpdateManyInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PurchasedProductListRelationFilter = {
  every?: Prisma.PurchasedProductWhereInput
  some?: Prisma.PurchasedProductWhereInput
  none?: Prisma.PurchasedProductWhereInput
}

export type PurchasedProductOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PurchasedProductOrderByRelevanceInput = {
  fields: Prisma.PurchasedProductOrderByRelevanceFieldEnum | Prisma.PurchasedProductOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PurchasedProductCountOrderByAggregateInput = {
  acquiredId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  TransactionString?: Prisma.SortOrder
  PhoneNumber?: Prisma.SortOrder
  Amount?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  MerchantRequestID?: Prisma.SortOrder
  product?: Prisma.SortOrder
  ResultCode?: Prisma.SortOrder
}

export type PurchasedProductAvgOrderByAggregateInput = {
  Amount?: Prisma.SortOrder
}

export type PurchasedProductMaxOrderByAggregateInput = {
  acquiredId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  TransactionString?: Prisma.SortOrder
  PhoneNumber?: Prisma.SortOrder
  Amount?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  MerchantRequestID?: Prisma.SortOrder
  product?: Prisma.SortOrder
  ResultCode?: Prisma.SortOrder
}

export type PurchasedProductMinOrderByAggregateInput = {
  acquiredId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  TransactionString?: Prisma.SortOrder
  PhoneNumber?: Prisma.SortOrder
  Amount?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  MerchantRequestID?: Prisma.SortOrder
  product?: Prisma.SortOrder
  ResultCode?: Prisma.SortOrder
}

export type PurchasedProductSumOrderByAggregateInput = {
  Amount?: Prisma.SortOrder
}

export type PurchasedProductCreateNestedManyWithoutPurchasedIdInput = {
  create?: Prisma.XOR<Prisma.PurchasedProductCreateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput> | Prisma.PurchasedProductCreateWithoutPurchasedIdInput[] | Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput[]
  connectOrCreate?: Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput | Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput[]
  createMany?: Prisma.PurchasedProductCreateManyPurchasedIdInputEnvelope
  connect?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
}

export type PurchasedProductUncheckedCreateNestedManyWithoutPurchasedIdInput = {
  create?: Prisma.XOR<Prisma.PurchasedProductCreateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput> | Prisma.PurchasedProductCreateWithoutPurchasedIdInput[] | Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput[]
  connectOrCreate?: Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput | Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput[]
  createMany?: Prisma.PurchasedProductCreateManyPurchasedIdInputEnvelope
  connect?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
}

export type PurchasedProductUpdateManyWithoutPurchasedIdNestedInput = {
  create?: Prisma.XOR<Prisma.PurchasedProductCreateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput> | Prisma.PurchasedProductCreateWithoutPurchasedIdInput[] | Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput[]
  connectOrCreate?: Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput | Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput[]
  upsert?: Prisma.PurchasedProductUpsertWithWhereUniqueWithoutPurchasedIdInput | Prisma.PurchasedProductUpsertWithWhereUniqueWithoutPurchasedIdInput[]
  createMany?: Prisma.PurchasedProductCreateManyPurchasedIdInputEnvelope
  set?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  disconnect?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  delete?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  connect?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  update?: Prisma.PurchasedProductUpdateWithWhereUniqueWithoutPurchasedIdInput | Prisma.PurchasedProductUpdateWithWhereUniqueWithoutPurchasedIdInput[]
  updateMany?: Prisma.PurchasedProductUpdateManyWithWhereWithoutPurchasedIdInput | Prisma.PurchasedProductUpdateManyWithWhereWithoutPurchasedIdInput[]
  deleteMany?: Prisma.PurchasedProductScalarWhereInput | Prisma.PurchasedProductScalarWhereInput[]
}

export type PurchasedProductUncheckedUpdateManyWithoutPurchasedIdNestedInput = {
  create?: Prisma.XOR<Prisma.PurchasedProductCreateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput> | Prisma.PurchasedProductCreateWithoutPurchasedIdInput[] | Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput[]
  connectOrCreate?: Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput | Prisma.PurchasedProductCreateOrConnectWithoutPurchasedIdInput[]
  upsert?: Prisma.PurchasedProductUpsertWithWhereUniqueWithoutPurchasedIdInput | Prisma.PurchasedProductUpsertWithWhereUniqueWithoutPurchasedIdInput[]
  createMany?: Prisma.PurchasedProductCreateManyPurchasedIdInputEnvelope
  set?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  disconnect?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  delete?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  connect?: Prisma.PurchasedProductWhereUniqueInput | Prisma.PurchasedProductWhereUniqueInput[]
  update?: Prisma.PurchasedProductUpdateWithWhereUniqueWithoutPurchasedIdInput | Prisma.PurchasedProductUpdateWithWhereUniqueWithoutPurchasedIdInput[]
  updateMany?: Prisma.PurchasedProductUpdateManyWithWhereWithoutPurchasedIdInput | Prisma.PurchasedProductUpdateManyWithWhereWithoutPurchasedIdInput[]
  deleteMany?: Prisma.PurchasedProductScalarWhereInput | Prisma.PurchasedProductScalarWhereInput[]
}

export type PurchasedProductCreateWithoutPurchasedIdInput = {
  acquiredId?: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount?: number
  Location: string
  MerchantRequestID?: string
  ResultCode?: string
}

export type PurchasedProductUncheckedCreateWithoutPurchasedIdInput = {
  acquiredId?: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount?: number
  Location: string
  MerchantRequestID?: string
  ResultCode?: string
}

export type PurchasedProductCreateOrConnectWithoutPurchasedIdInput = {
  where: Prisma.PurchasedProductWhereUniqueInput
  create: Prisma.XOR<Prisma.PurchasedProductCreateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput>
}

export type PurchasedProductCreateManyPurchasedIdInputEnvelope = {
  data: Prisma.PurchasedProductCreateManyPurchasedIdInput | Prisma.PurchasedProductCreateManyPurchasedIdInput[]
  skipDuplicates?: boolean
}

export type PurchasedProductUpsertWithWhereUniqueWithoutPurchasedIdInput = {
  where: Prisma.PurchasedProductWhereUniqueInput
  update: Prisma.XOR<Prisma.PurchasedProductUpdateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedUpdateWithoutPurchasedIdInput>
  create: Prisma.XOR<Prisma.PurchasedProductCreateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedCreateWithoutPurchasedIdInput>
}

export type PurchasedProductUpdateWithWhereUniqueWithoutPurchasedIdInput = {
  where: Prisma.PurchasedProductWhereUniqueInput
  data: Prisma.XOR<Prisma.PurchasedProductUpdateWithoutPurchasedIdInput, Prisma.PurchasedProductUncheckedUpdateWithoutPurchasedIdInput>
}

export type PurchasedProductUpdateManyWithWhereWithoutPurchasedIdInput = {
  where: Prisma.PurchasedProductScalarWhereInput
  data: Prisma.XOR<Prisma.PurchasedProductUpdateManyMutationInput, Prisma.PurchasedProductUncheckedUpdateManyWithoutPurchasedIdInput>
}

export type PurchasedProductScalarWhereInput = {
  AND?: Prisma.PurchasedProductScalarWhereInput | Prisma.PurchasedProductScalarWhereInput[]
  OR?: Prisma.PurchasedProductScalarWhereInput[]
  NOT?: Prisma.PurchasedProductScalarWhereInput | Prisma.PurchasedProductScalarWhereInput[]
  acquiredId?: Prisma.StringFilter<"PurchasedProduct"> | string
  productId?: Prisma.StringFilter<"PurchasedProduct"> | string
  TransactionString?: Prisma.StringFilter<"PurchasedProduct"> | string
  PhoneNumber?: Prisma.StringFilter<"PurchasedProduct"> | string
  Amount?: Prisma.IntFilter<"PurchasedProduct"> | number
  Location?: Prisma.StringFilter<"PurchasedProduct"> | string
  MerchantRequestID?: Prisma.StringFilter<"PurchasedProduct"> | string
  product?: Prisma.StringFilter<"PurchasedProduct"> | string
  ResultCode?: Prisma.StringFilter<"PurchasedProduct"> | string
}

export type PurchasedProductCreateManyPurchasedIdInput = {
  acquiredId?: string
  productId: string
  TransactionString: string
  PhoneNumber: string
  Amount?: number
  Location: string
  MerchantRequestID?: string
  ResultCode?: string
}

export type PurchasedProductUpdateWithoutPurchasedIdInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PurchasedProductUncheckedUpdateWithoutPurchasedIdInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PurchasedProductUncheckedUpdateManyWithoutPurchasedIdInput = {
  acquiredId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  TransactionString?: Prisma.StringFieldUpdateOperationsInput | string
  PhoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  Amount?: Prisma.IntFieldUpdateOperationsInput | number
  Location?: Prisma.StringFieldUpdateOperationsInput | string
  MerchantRequestID?: Prisma.StringFieldUpdateOperationsInput | string
  ResultCode?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PurchasedProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  acquiredId?: boolean
  productId?: boolean
  TransactionString?: boolean
  PhoneNumber?: boolean
  Amount?: boolean
  Location?: boolean
  MerchantRequestID?: boolean
  product?: boolean
  ResultCode?: boolean
  purchasedId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["purchasedProduct"]>

export type PurchasedProductSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  acquiredId?: boolean
  productId?: boolean
  TransactionString?: boolean
  PhoneNumber?: boolean
  Amount?: boolean
  Location?: boolean
  MerchantRequestID?: boolean
  product?: boolean
  ResultCode?: boolean
  purchasedId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["purchasedProduct"]>

export type PurchasedProductSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  acquiredId?: boolean
  productId?: boolean
  TransactionString?: boolean
  PhoneNumber?: boolean
  Amount?: boolean
  Location?: boolean
  MerchantRequestID?: boolean
  product?: boolean
  ResultCode?: boolean
  purchasedId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["purchasedProduct"]>

export type PurchasedProductSelectScalar = {
  acquiredId?: boolean
  productId?: boolean
  TransactionString?: boolean
  PhoneNumber?: boolean
  Amount?: boolean
  Location?: boolean
  MerchantRequestID?: boolean
  product?: boolean
  ResultCode?: boolean
}

export type PurchasedProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"acquiredId" | "productId" | "TransactionString" | "PhoneNumber" | "Amount" | "Location" | "MerchantRequestID" | "product" | "ResultCode", ExtArgs["result"]["purchasedProduct"]>
export type PurchasedProductInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  purchasedId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>
}
export type PurchasedProductIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  purchasedId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>
}
export type PurchasedProductIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  purchasedId?: boolean | Prisma.ProductsDefaultArgs<ExtArgs>
}

export type $PurchasedProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PurchasedProduct"
  objects: {
    purchasedId: Prisma.$ProductsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    acquiredId: string
    productId: string
    TransactionString: string
    PhoneNumber: string
    Amount: number
    Location: string
    MerchantRequestID: string
    product: string
    ResultCode: string
  }, ExtArgs["result"]["purchasedProduct"]>
  composites: {}
}

export type PurchasedProductGetPayload<S extends boolean | null | undefined | PurchasedProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload, S>

export type PurchasedProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PurchasedProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PurchasedProductCountAggregateInputType | true
  }

export interface PurchasedProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PurchasedProduct'], meta: { name: 'PurchasedProduct' } }
  /**
   * Find zero or one PurchasedProduct that matches the filter.
   * @param {PurchasedProductFindUniqueArgs} args - Arguments to find a PurchasedProduct
   * @example
   * // Get one PurchasedProduct
   * const purchasedProduct = await prisma.purchasedProduct.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PurchasedProductFindUniqueArgs>(args: Prisma.SelectSubset<T, PurchasedProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PurchasedProduct that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PurchasedProductFindUniqueOrThrowArgs} args - Arguments to find a PurchasedProduct
   * @example
   * // Get one PurchasedProduct
   * const purchasedProduct = await prisma.purchasedProduct.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PurchasedProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PurchasedProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PurchasedProduct that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductFindFirstArgs} args - Arguments to find a PurchasedProduct
   * @example
   * // Get one PurchasedProduct
   * const purchasedProduct = await prisma.purchasedProduct.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PurchasedProductFindFirstArgs>(args?: Prisma.SelectSubset<T, PurchasedProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PurchasedProduct that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductFindFirstOrThrowArgs} args - Arguments to find a PurchasedProduct
   * @example
   * // Get one PurchasedProduct
   * const purchasedProduct = await prisma.purchasedProduct.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PurchasedProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PurchasedProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PurchasedProducts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PurchasedProducts
   * const purchasedProducts = await prisma.purchasedProduct.findMany()
   * 
   * // Get first 10 PurchasedProducts
   * const purchasedProducts = await prisma.purchasedProduct.findMany({ take: 10 })
   * 
   * // Only select the `acquiredId`
   * const purchasedProductWithAcquiredIdOnly = await prisma.purchasedProduct.findMany({ select: { acquiredId: true } })
   * 
   */
  findMany<T extends PurchasedProductFindManyArgs>(args?: Prisma.SelectSubset<T, PurchasedProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PurchasedProduct.
   * @param {PurchasedProductCreateArgs} args - Arguments to create a PurchasedProduct.
   * @example
   * // Create one PurchasedProduct
   * const PurchasedProduct = await prisma.purchasedProduct.create({
   *   data: {
   *     // ... data to create a PurchasedProduct
   *   }
   * })
   * 
   */
  create<T extends PurchasedProductCreateArgs>(args: Prisma.SelectSubset<T, PurchasedProductCreateArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PurchasedProducts.
   * @param {PurchasedProductCreateManyArgs} args - Arguments to create many PurchasedProducts.
   * @example
   * // Create many PurchasedProducts
   * const purchasedProduct = await prisma.purchasedProduct.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PurchasedProductCreateManyArgs>(args?: Prisma.SelectSubset<T, PurchasedProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PurchasedProducts and returns the data saved in the database.
   * @param {PurchasedProductCreateManyAndReturnArgs} args - Arguments to create many PurchasedProducts.
   * @example
   * // Create many PurchasedProducts
   * const purchasedProduct = await prisma.purchasedProduct.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PurchasedProducts and only return the `acquiredId`
   * const purchasedProductWithAcquiredIdOnly = await prisma.purchasedProduct.createManyAndReturn({
   *   select: { acquiredId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PurchasedProductCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PurchasedProductCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PurchasedProduct.
   * @param {PurchasedProductDeleteArgs} args - Arguments to delete one PurchasedProduct.
   * @example
   * // Delete one PurchasedProduct
   * const PurchasedProduct = await prisma.purchasedProduct.delete({
   *   where: {
   *     // ... filter to delete one PurchasedProduct
   *   }
   * })
   * 
   */
  delete<T extends PurchasedProductDeleteArgs>(args: Prisma.SelectSubset<T, PurchasedProductDeleteArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PurchasedProduct.
   * @param {PurchasedProductUpdateArgs} args - Arguments to update one PurchasedProduct.
   * @example
   * // Update one PurchasedProduct
   * const purchasedProduct = await prisma.purchasedProduct.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PurchasedProductUpdateArgs>(args: Prisma.SelectSubset<T, PurchasedProductUpdateArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PurchasedProducts.
   * @param {PurchasedProductDeleteManyArgs} args - Arguments to filter PurchasedProducts to delete.
   * @example
   * // Delete a few PurchasedProducts
   * const { count } = await prisma.purchasedProduct.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PurchasedProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, PurchasedProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PurchasedProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PurchasedProducts
   * const purchasedProduct = await prisma.purchasedProduct.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PurchasedProductUpdateManyArgs>(args: Prisma.SelectSubset<T, PurchasedProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PurchasedProducts and returns the data updated in the database.
   * @param {PurchasedProductUpdateManyAndReturnArgs} args - Arguments to update many PurchasedProducts.
   * @example
   * // Update many PurchasedProducts
   * const purchasedProduct = await prisma.purchasedProduct.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PurchasedProducts and only return the `acquiredId`
   * const purchasedProductWithAcquiredIdOnly = await prisma.purchasedProduct.updateManyAndReturn({
   *   select: { acquiredId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PurchasedProductUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PurchasedProductUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PurchasedProduct.
   * @param {PurchasedProductUpsertArgs} args - Arguments to update or create a PurchasedProduct.
   * @example
   * // Update or create a PurchasedProduct
   * const purchasedProduct = await prisma.purchasedProduct.upsert({
   *   create: {
   *     // ... data to create a PurchasedProduct
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PurchasedProduct we want to update
   *   }
   * })
   */
  upsert<T extends PurchasedProductUpsertArgs>(args: Prisma.SelectSubset<T, PurchasedProductUpsertArgs<ExtArgs>>): Prisma.Prisma__PurchasedProductClient<runtime.Types.Result.GetResult<Prisma.$PurchasedProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PurchasedProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductCountArgs} args - Arguments to filter PurchasedProducts to count.
   * @example
   * // Count the number of PurchasedProducts
   * const count = await prisma.purchasedProduct.count({
   *   where: {
   *     // ... the filter for the PurchasedProducts we want to count
   *   }
   * })
  **/
  count<T extends PurchasedProductCountArgs>(
    args?: Prisma.Subset<T, PurchasedProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PurchasedProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PurchasedProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PurchasedProductAggregateArgs>(args: Prisma.Subset<T, PurchasedProductAggregateArgs>): Prisma.PrismaPromise<GetPurchasedProductAggregateType<T>>

  /**
   * Group by PurchasedProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PurchasedProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PurchasedProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PurchasedProductGroupByArgs['orderBy'] }
      : { orderBy?: PurchasedProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PurchasedProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPurchasedProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PurchasedProduct model
 */
readonly fields: PurchasedProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PurchasedProduct.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PurchasedProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  purchasedId<T extends Prisma.ProductsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductsDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductsClient<runtime.Types.Result.GetResult<Prisma.$ProductsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PurchasedProduct model
 */
export interface PurchasedProductFieldRefs {
  readonly acquiredId: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly productId: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly TransactionString: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly PhoneNumber: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly Amount: Prisma.FieldRef<"PurchasedProduct", 'Int'>
  readonly Location: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly MerchantRequestID: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly product: Prisma.FieldRef<"PurchasedProduct", 'String'>
  readonly ResultCode: Prisma.FieldRef<"PurchasedProduct", 'String'>
}
    

// Custom InputTypes
/**
 * PurchasedProduct findUnique
 */
export type PurchasedProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * Filter, which PurchasedProduct to fetch.
   */
  where: Prisma.PurchasedProductWhereUniqueInput
}

/**
 * PurchasedProduct findUniqueOrThrow
 */
export type PurchasedProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * Filter, which PurchasedProduct to fetch.
   */
  where: Prisma.PurchasedProductWhereUniqueInput
}

/**
 * PurchasedProduct findFirst
 */
export type PurchasedProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * Filter, which PurchasedProduct to fetch.
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PurchasedProducts to fetch.
   */
  orderBy?: Prisma.PurchasedProductOrderByWithRelationInput | Prisma.PurchasedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PurchasedProducts.
   */
  cursor?: Prisma.PurchasedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PurchasedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PurchasedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PurchasedProducts.
   */
  distinct?: Prisma.PurchasedProductScalarFieldEnum | Prisma.PurchasedProductScalarFieldEnum[]
}

/**
 * PurchasedProduct findFirstOrThrow
 */
export type PurchasedProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * Filter, which PurchasedProduct to fetch.
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PurchasedProducts to fetch.
   */
  orderBy?: Prisma.PurchasedProductOrderByWithRelationInput | Prisma.PurchasedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PurchasedProducts.
   */
  cursor?: Prisma.PurchasedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PurchasedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PurchasedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PurchasedProducts.
   */
  distinct?: Prisma.PurchasedProductScalarFieldEnum | Prisma.PurchasedProductScalarFieldEnum[]
}

/**
 * PurchasedProduct findMany
 */
export type PurchasedProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * Filter, which PurchasedProducts to fetch.
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PurchasedProducts to fetch.
   */
  orderBy?: Prisma.PurchasedProductOrderByWithRelationInput | Prisma.PurchasedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PurchasedProducts.
   */
  cursor?: Prisma.PurchasedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PurchasedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PurchasedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PurchasedProducts.
   */
  distinct?: Prisma.PurchasedProductScalarFieldEnum | Prisma.PurchasedProductScalarFieldEnum[]
}

/**
 * PurchasedProduct create
 */
export type PurchasedProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * The data needed to create a PurchasedProduct.
   */
  data: Prisma.XOR<Prisma.PurchasedProductCreateInput, Prisma.PurchasedProductUncheckedCreateInput>
}

/**
 * PurchasedProduct createMany
 */
export type PurchasedProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PurchasedProducts.
   */
  data: Prisma.PurchasedProductCreateManyInput | Prisma.PurchasedProductCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PurchasedProduct createManyAndReturn
 */
export type PurchasedProductCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * The data used to create many PurchasedProducts.
   */
  data: Prisma.PurchasedProductCreateManyInput | Prisma.PurchasedProductCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PurchasedProduct update
 */
export type PurchasedProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * The data needed to update a PurchasedProduct.
   */
  data: Prisma.XOR<Prisma.PurchasedProductUpdateInput, Prisma.PurchasedProductUncheckedUpdateInput>
  /**
   * Choose, which PurchasedProduct to update.
   */
  where: Prisma.PurchasedProductWhereUniqueInput
}

/**
 * PurchasedProduct updateMany
 */
export type PurchasedProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PurchasedProducts.
   */
  data: Prisma.XOR<Prisma.PurchasedProductUpdateManyMutationInput, Prisma.PurchasedProductUncheckedUpdateManyInput>
  /**
   * Filter which PurchasedProducts to update
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * Limit how many PurchasedProducts to update.
   */
  limit?: number
}

/**
 * PurchasedProduct updateManyAndReturn
 */
export type PurchasedProductUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * The data used to update PurchasedProducts.
   */
  data: Prisma.XOR<Prisma.PurchasedProductUpdateManyMutationInput, Prisma.PurchasedProductUncheckedUpdateManyInput>
  /**
   * Filter which PurchasedProducts to update
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * Limit how many PurchasedProducts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PurchasedProduct upsert
 */
export type PurchasedProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * The filter to search for the PurchasedProduct to update in case it exists.
   */
  where: Prisma.PurchasedProductWhereUniqueInput
  /**
   * In case the PurchasedProduct found by the `where` argument doesn't exist, create a new PurchasedProduct with this data.
   */
  create: Prisma.XOR<Prisma.PurchasedProductCreateInput, Prisma.PurchasedProductUncheckedCreateInput>
  /**
   * In case the PurchasedProduct was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PurchasedProductUpdateInput, Prisma.PurchasedProductUncheckedUpdateInput>
}

/**
 * PurchasedProduct delete
 */
export type PurchasedProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
  /**
   * Filter which PurchasedProduct to delete.
   */
  where: Prisma.PurchasedProductWhereUniqueInput
}

/**
 * PurchasedProduct deleteMany
 */
export type PurchasedProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PurchasedProducts to delete
   */
  where?: Prisma.PurchasedProductWhereInput
  /**
   * Limit how many PurchasedProducts to delete.
   */
  limit?: number
}

/**
 * PurchasedProduct without action
 */
export type PurchasedProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PurchasedProduct
   */
  select?: Prisma.PurchasedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PurchasedProduct
   */
  omit?: Prisma.PurchasedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchasedProductInclude<ExtArgs> | null
}
